"""Add folder and advanced file support to FileEntry

Revision ID: fff2ecc6088d
Revises: c26cb80317b5
Create Date: 2025-07-15 20:07:12.527642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff2ecc6088d'
down_revision: Union[str, Sequence[str], None] = 'c26cb80317b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fileentry', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('fileentry', sa.Column('is_folder', sa.Boolean(), nullable=True))
    op.add_column('fileentry', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('fileentry', sa.Column('file_type', sa.String(), nullable=True))
    op.create_foreign_key(None, 'fileentry', 'fileentry', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fileentry', type_='foreignkey')
    op.drop_column('fileentry', 'file_type')
    op.drop_column('fileentry', 'size')
    op.drop_column('fileentry', 'is_folder')
    op.drop_column('fileentry', 'parent_id')
    # ### end Alembic commands ###
